### ISSUE TITLE
WebAssembly Support

### ISSUE THREAD

**Issue by rylev** [peterhuene/azure-functions-rs#219]
## Feature Request 
Currently Rust functions can only be run as containers which comes with the unfortunate side effect of not having usage based pricing. 

## Solution
Node functions come with WASM support, so we could write a wrapper around Rust functions that marshall through node instead of talking directly to the functions runtime. 

## Alternatives
We could also just not do this, and try to convince the functions team to allow for first class Rust support or usage based pricing for containers

**Comment by peterhuene** [comment]
This would be an interesting approach!

From what limited context I have to work from to design this, at first glance it seems like that would be an improvement for the node worker to seamlessly interop with WASM-targeted languages, including Rust.

I don't see much work we can do in the Rust worker to support this functionality; it would probably be better served as another initiative that enhances the capability of the node worker.

My goal is to get as much of this project feature complete so that the Functions team might officially support it (or at least experimental) so we can use consumption model; I definitely don't want to have to use containers as the sole means of running this in production.

**Comment by peterhuene** [comment]
@rylev I think the path going forward for this project is for official support so that it can one day be used from a consumption plan.

![](https://media2.giphy.com/media/s90oiV9deQU7e/giphy.gif)

I think there's exciting potential for a language-agnostic WASM-based worker (plus, it would be awesome to use wasmer/wasmtime), but I think that would be best done as a separate initiative; however, that would also run into the same problem of not being a first-party supported worker.

My goal with this project is obtaining as much parity with the CLR languages as possible given the restrictions placed on the out-of-proc worker model.  As I believe a Rust-native solution to be the best way to achieve that, I'm going to close this issue for now.
