### ISSUE TITLE
Unable to run locally on Linux

### ISSUE THREAD

**Issue by rtyler** [peterhuene/azure-functions-rs#231]
I believe the README is missing an prerequisite when working on Linux, the `dotnet` runtime appears to need to exist in order to run the function locally

## Steps to reproduce

* Create a function on a Linux machine with Rust installed
* Attempt to run `cargo func run`

## Expected  behavior

Service on localhost :smile: 

## Actual behavior

```
cargo func run                                 
🚀 spawning 'cargo' to initialize script root: cargo run -- init --script-root /tmp/script-root.O2OLZGb1iuh2 --sync ️✓
    Finished dev [unoptimized + debuginfo] target(s) in 0.12s
     Running `target/debug/pleasenotifyus init --script-root /tmp/script-root.O2OLZGb1iuh2 --sync`                                   
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "failed to spawn dotnet: No such file or directory (os error 2
)"', src/libcore/result.rs:997:5                                                                                                     
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.                                                       
error: cargo failed with exit code 101.       
```

**Comment by rtyler** [comment]
This seems to also affect building with the generated `Dockerfile`, referenced below, the output for my newly generated function is:

```
#15 317.1    Compiling grpcio-compiler v0.5.0-alpha
#15 319.8    Compiling protoc-grpcio v1.0.2
#15 320.1    Compiling azure-functions-shared v0.6.0
#15 335.9    Compiling azure-functions-codegen v0.6.0
#15 345.3    Compiling azure-functions v0.6.0
#15 359.1    Compiling pleasenotifyus v0.1.0 (/src)
#15 359.4 warning: unused variable: `req`
#15 359.4  --> src/functions/ingest.rs:7:15
#15 359.4   |
#15 359.4 7 | pub fn ingest(req: HttpRequest) -> HttpResponse {
#15 359.4   |               ^^^ help: consider using `_req` instead
#15 359.4   |
#15 359.4   = note: #[warn(unused_variables)] on by default
#15 359.4
#15 359.4 warning: unused variable: `trigger`
#15 359.4  --> src/functions/dispatch.rs:8:17
#15 359.4   |
#15 359.4 8 | pub fn dispatch(trigger: EventHubTrigger) {
#15 359.4   |                 ^^^^^^^ help: consider using `_trigger` instead
#15 359.4
#15 364.3     Finished release [optimized] target(s) in 6m 03s
#15 364.3      Running `target/release/pleasenotifyus init --script-root /home/site/wwwroot --sync`                                   
#15 364.4 thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "failed to spawn dotnet: No such file or directory (os error 2)"', src/libcore/result.rs:997:5
#15 364.4 note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
------
rpc error: code = Unknown desc = executor failed running [cargo run --release -- init --script-root /home/site/wwwroot --sync]: exit code: 101
make: *** [Makefile:23: container] Error 1
```


```dockerfile
FROM peterhuene/azure-functions-rs-build:0.6.0 AS build-image

WORKDIR /src
COPY . /src

# Run with mounted cache
RUN --mount=type=cache,target=/src/target \
    --mount=type=cache,target=/usr/local/cargo/git \
    --mount=type=cache,target=/usr/local/cargo/registry \
    ["cargo", "run", "--release", "--", "init", "--script-root", "/home/site/wwwroot", "--sync"]

FROM mcr.microsoft.com/azure-functions/base:2.0 as runtime-image

FROM microsoft/dotnet:2.2-aspnetcore-runtime

ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    HOME=/home \
    FUNCTIONS_WORKER_RUNTIME=Rust \
    languageWorkers__workersDirectory=/home/site/wwwroot/workers

# Copy the Azure Functions host from the runtime image
COPY --from=runtime-image [ "/azure-functions-host", "/azure-functions-host" ]

# Copy configuration to the Azure Functions Host
COPY --from=build-image ["/src/appsettings.json", "/azure-functions-host/appsettings.json"]

# Copy the script root contents from the build image
COPY --from=build-image ["/home/site/wwwroot", "/home/site/wwwroot"]

WORKDIR /home/site/wwwroot
CMD [ "dotnet", "/azure-functions-host/Microsoft.Azure.WebJobs.Script.WebHost.dll" ]
```

**Comment by rtyler** [comment]
Modifying the `Dockerfile` (see below) allows the Dockerfile to be run, and it doesn't appear to have had a negative impact on the ability of the function to run within the container.


```diff
diff --git a/Dockerfile b/Dockerfile
index 92dca14..fb5f7f4 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -9,7 +9,7 @@ COPY . /src
 RUN --mount=type=cache,target=/src/target \
     --mount=type=cache,target=/usr/local/cargo/git \
     --mount=type=cache,target=/usr/local/cargo/registry \
-    ["cargo", "run", "--release", "--", "init", "--script-root", "/home/site/wwwroot", "--sync"]
+    ["cargo", "run", "--release", "--", "init", "--script-root", "/home/site/wwwroot"]
 
 FROM mcr.microsoft.com/azure-functions/base:2.0 as runtime-image
```

**Comment by peterhuene** [comment]
Hi @rtyler. Thanks for reporting the issue to me.

What distro are you running on?  I expected the Azure Function Core Tools to have a dependency on .NET Core since the Azure Functions Host is implemented in .NET.  Perhaps it is installing as a self-contained install (i.e. private) and thus isn't installing a system-wide .NET Core.

For now you can work around the issue by installing a .NET Core SDK >= 2.1.300 (any recent 2.1/2.2 SDK should work).  I'm going to investigate using the Azure Functions Core Tools to do the extensions sync.

Without `--sync`, it does not attempt to download any of the binding extensions; since they are packaged as NuGet packages, we use the .NET Core SDK to download and publish them into your "script root" (where the application would run from via Azure Functions).  This is only necessary if you use any binding type other than the HTTP ones (storage, cosmos db, etc.).

Regarding the base Docker build image not having dotnet on the PATH, that's something I can fix right now.

Thanks!

**Comment by rtyler** [comment]
Turns out if you install `azure-functions-core-tools` from NPM, then there's no `dotnet` executable unpacked.

I'm using openSUSE, but I believe any Red Hat/CentOS user would also have issues because the Azure Functions Core Tools are not currently packaged for rpm-based distributions as far as I can tell.

**Comment by rtyler** [comment]
somewhat related `cargo func run` is a curious beast because it uses that temp directory, some of my relative paths, like that to `func` originally didn't work. :man_shrugging: 


Moving forward at least :smile:

**Comment by peterhuene** [comment]
It uses a temp directory by default, but you can explicitly specify a script root to initialize to with `cargo func run --script-root <dir>`.

Which relative paths are you referring to?

**Comment by rtyler** [comment]
These were relative paths in my environment, I tend to avoid installing node packages globally since they tend to do who-knows-what :smile_cat:

**Comment by peterhuene** [comment]
I have a fix for the base Docker image to include a dotnet SDK to sync extensions that I'll push up shortly.

Unfortunately it looks like the Azure Functions Core Tools also rely on a global SDK install to sync extensions, so the end result is the same.

I'll add a .NET Core SDK as a dependency wherever it's missing in the documentation.

Additionally, I discovered that the base images for the Azure Functions Host changed and we can save ~150MB off of deployment image by using `mcr.microsoft.com/dotnet/core/runtime-deps` instead of `dotnet:2.2-aspnetcore-runtime`.

You can apply this to an existing `Dockerfile` generated with `cargo func new-app` like so:

```
@@ -13,7 +13,7 @@ RUN --mount=type=cache,target=/src/target \

 FROM mcr.microsoft.com/azure-functions/base:2.0 as runtime-image

-FROM microsoft/dotnet:2.2-aspnetcore-runtime
+FROM mcr.microsoft.com/dotnet/core/runtime-deps:2.2

 ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
     HOME=/home \
@@ -30,4 +30,4 @@ COPY --from=build-image ["/src/appsettings.json", "/azure-functions-host/appsett
 COPY --from=build-image ["/home/site/wwwroot", "/home/site/wwwroot"]

 WORKDIR /home/site/wwwroot
-CMD [ "dotnet", "/azure-functions-host/Microsoft.Azure.WebJobs.Script.WebHost.dll" ]
+CMD [ "/azure-functions-host/Microsoft.Azure.WebJobs.Script.WebHost" ]
```

I'll be updating the template to generate this.

**Comment by peterhuene** [comment]
I've pushed up an updated 0.6.0 image.

If you do `docker pull peterhuene/azure-functions-rs-build:0.6.0` you should now be able to create the deployment image when syncing extensions.
